config/routes.rb
Rails.application.routes.draw do
  resources :perros
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/perro.rb
class Perro < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/perros_controller.rb
class PerrosController < ApplicationController
  before_action :set_perro, only: [:show, :edit, :update, :destroy]

  # GET /perros
  # GET /perros.json
  def index
    @perros = Perro.all
  end

  # GET /perros/1
  # GET /perros/1.json
  def show
  end

  # GET /perros/new
  def new
    @perro = Perro.new
  end

  # GET /perros/1/edit
  def edit
  end

  # POST /perros
  # POST /perros.json
  def create
    @perro = Perro.new(perro_params)

    respond_to do |format|
      if @perro.save
        format.html { redirect_to @perro, notice: 'Perro was successfully created.' }
        format.json { render :show, status: :created, location: @perro }
      else
        format.html { render :new }
        format.json { render json: @perro.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /perros/1
  # PATCH/PUT /perros/1.json
  def update
    respond_to do |format|
      if @perro.update(perro_params)
        format.html { redirect_to @perro, notice: 'Perro was successfully updated.' }
        format.json { render :show, status: :ok, location: @perro }
      else
        format.html { render :edit }
        format.json { render json: @perro.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /perros/1
  # DELETE /perros/1.json
  def destroy
    @perro.destroy
    respond_to do |format|
      format.html { redirect_to perros_url, notice: 'Perro was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_perro
      @perro = Perro.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def perro_params
      params.require(:perro).permit(:nombre, :direccion, :localidad, :edad, :vive)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/perros_helper.rb
module PerrosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Animal</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/perros/_form.html.erb
<%= form_with(model: perro, local: true) do |form| %>
  <% if perro.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(perro.errors.count, "error") %> prohibited this perro from being saved:</h2>

      <ul>
      <% perro.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nombre %>
    <%= form.text_field :nombre %>
  </div>

  <div class="field">
    <%= form.label :direccion %>
    <%= form.text_area :direccion %>
  </div>

  <div class="field">
    <%= form.label :localidad %>
    <%= form.text_area :localidad %>
  </div>

  <div class="field">
    <%= form.label :edad %>
    <%= form.number_field :edad %>
  </div>

  <div class="field">
    <%= form.label :vive %>
    <%= form.check_box :vive %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/perros/edit.html.erb
<h1>Editing Perro</h1>

<%= render 'form', perro: @perro %>

<%= link_to 'Show', @perro %> |
<%= link_to 'Back', perros_path %>

app/views/perros/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Perros</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Direccion</th>
      <th>Localidad</th>
      <th>Edad</th>
      <th>Vive</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @perros.each do |perro| %>
      <tr>
        <td><%= perro.nombre %></td>
        <td><%= perro.direccion %></td>
        <td><%= perro.localidad %></td>Are you sure
        <td><%= perro.edad %></td>
        <td><%= perro.vive %></td>
        <td><%= link_to 'Mostrar', perro %></td>
        <td><%= link_to 'Editar', edit_perro_path(perro) %></td>
        <td><%= link_to 'Borrar', perro, method: :delete, data: { confirm: 'Esta Usted Seguro?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nuevo Perro', new_perro_path %>

app/views/perros/new.html.erb
<h1>New Perro</h1>

<%= render 'form', perro: @perro %>

<%= link_to 'Volver', perros_path %>

app/views/perros/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @perro.nombre %>
</p>

<p>
  <strong>Direccion:</strong>
  <%= @perro.direccion %>
</p>

<p>
  <strong>Localidad:</strong>
  <%= @perro.localidad %>
</p>

<p>
  <strong>Edad:</strong>
  <%= @perro.edad %>
</p>

<p>
  <strong>Vive:</strong>
  <%= @perro.vive %>
</p>

<%= link_to 'Editar', edit_perro_path(@perro) %> |
<%= link_to 'Volver', perros_path %>